export interface BenchmarkRow {
  model: string;
  short: string;
  recall: number;
  falseNegativeRate: number;
  auprc: number;
  brier: number | null;
  leadMinutes: number;
  falseAlarmsPer24h: number;
  recommended: boolean;
}

// Generated by `python -m ml.train --output-dir artifacts` from artifacts/metrics.json.
// ScenarioBench is fully simulated; these values are not field-performance claims.
export const BENCHMARKS: BenchmarkRow[] = [
  {
    model: "Single-sensor threshold",
    short: "DEVICE",
    recall: 0.2,
    falseNegativeRate: 0.8,
    auprc: 0.813065,
    brier: 0.24212,
    leadMinutes: 5,
    falseAlarmsPer24h: 7.5,
    recommended: false,
  },
  {
    model: "Process signals only",
    short: "PROCESS",
    recall: 1,
    falseNegativeRate: 0,
    auprc: 0.946734,
    brier: 0.070132,
    leadMinutes: 12,
    falseAlarmsPer24h: 8.653846,
    recommended: false,
  },
  {
    model: "Compound Zero fusion",
    short: "FULL FUSION",
    recall: 1,
    falseNegativeRate: 0,
    auprc: 0.99701,
    brier: 0.014616,
    leadMinutes: 12,
    falseAlarmsPer24h: 1.153846,
    recommended: true,
  },
];

export const VALIDATION_META = {
  dataset: "ScenarioBench v1.0.0",
  runId: "cz-sb1-96166a27",
  samples: 27_648,
  testSamples: 5_616,
  groups: 576,
  seeds: 64,
  split: "Whole-seed holdout; train/calibration/test seed overlap = 0",
  sha256: "96166a2762577a2fa8440e2a6f0f819c342aef9e9cf790e3ed2bef3eb6f4e314",
  disclosure: "SIMULATED process signals joined to authored work-context scenarios",
};

// Generated by `python -m ml.robustness_bench` from
// artifacts/robustness_metrics.json. These are controlled ScenarioBench
// diagnostics, not field-transfer or production-failure guarantees.
export const ROBUSTNESS_META = {
  source: "artifacts/robustness_metrics.json",
  classification: "SIMULATED ScenarioBench diagnostics",
  baseHoldout: {
    eventRecall: 1,
    detectedEvents: 65,
    eventGroups: 65,
    medianLeadMinutes: 12,
    expectedCalibrationError: 0.006335,
  },
  scenarioTypeHoldout: {
    eventRecall: 0.8,
    detectedEvents: 256,
    eventGroups: 320,
    folds: 9,
    eventBearingFolds: 5,
    failedScenarioType: "process_drift",
    failedScenarioRecall: 0,
    failedScenarioDetectedEvents: 0,
    failedScenarioEventGroups: 64,
  },
  missingStreams: {
    worstEventRecall: 0.8,
    detectedEvents: 52,
    eventGroups: 65,
    affectedCases: ["process sensor stream", "barrier + shift stream"],
  },
  sensorNoise: {
    sigma: 0.05,
    eventRecall: 1,
    baselineFalseAlarmsPer24h: 1.153846,
    stressedFalseAlarmsPer24h: 47.884615,
  },
  fieldGate:
    "Resolve unseen-scenario and missing-stream failures with authorized local data, site calibration and prospective shadow-mode validation before operational use.",
  claimBoundary:
    "Authored simulated data only; not field validation, safety certification or evidence of site-transfer performance.",
};
